version: '2.3'

x-runtime: &runtime
  # volumes:
  #   - ./src:/dst
  restart: always

x-environment: &environment
  DEBUG: 1

services:
  ci:
    <<: *runtime
    build:
      context: .
      dockerfile: ci/Dockerfile
      args:
        BASE_IMG: $BASE_IMG
    image: $REG/rt/$SRV:$CI
    ports:
      - 8880:8888
    env_file:
      - ./.env
    environment:
      <<: *environment
    volumes:
      - ./src:/srv
    command:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --port=8888
      - --no-browser
      - --notebook-dir="/srv"
      - --allow-root
      - --LabApp.token=
  rt:
    <<: *runtime
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMG: $BASE_IMG
    image: $REG/rt/$SRV:$RT
    env_file:
      - ./.env
    environment:
      <<: *environment

networks:
  default:
    external:
      name: rt_default